@token=COLE_AQUI_O_TOKEN_RETORNADO_POR_1auth.http
@tokenAdmin=COLE_AQUI_O_TOKEN_DO_ADMIN

# ====================================================================
# 2. ROTAS PROTEGIDAS DE USUÁRIOS
# ====================================================================

### Meu perfil (RF01)
GET http://localhost:3000/api/usuarios/perfil
Authorization: Bearer {{token}}

###

### Buscar Todos (RNF02 - só administrador)
GET http://localhost:3000/api/usuarios
Authorization: Bearer {{tokenAdmin}}

###

### Buscar Todos com token comum (deve retornar 401)
GET http://localhost:3000/api/usuarios
Authorization: Bearer {{token}}

###

### Buscar por ID específico
GET http://localhost:3000/api/usuarios/2
Authorization: Bearer {{token}}

###

### Atualizar Usuário (a senha é regravada com hash - RNF04)
PUT http://localhost:3000/api/usuarios/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "João Silva",
  "email": "joao@email.com",
  "senha": "1234"
}

###

### Tentar virar admin com token comum (deve retornar 401)
PUT http://localhost:3000/api/usuarios/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "role": "admin"
}

###

### Acessar dados de outro usuário (deve retornar 401 - RNF02)
GET http://localhost:3000/api/usuarios/1
Authorization: Bearer {{token}}

###

### Deletar Usuário
DELETE http://localhost:3000/api/usuarios/2
Authorization: Bearer {{token}}
